### ISSUE TITLE
Základní rozdělení rolí

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-PB138-2016#3]
> Taktéž se ověřuje základní rozdělení rolí při řešení projektu, což musí být zřetelně rozepsáno na wiki a všichni řešitelé musejí být v projektu na GH vedeni jako vývojáři.

**Comment by VikiVozarova** [comment]
JS Client - Filip (JavaScript, view)
API - Viki (Java, controller)
Model - Miška (komunikácia s databázou, odpovedanie na dotazy, XQuery)
Databáza - Soňa (XSD, XML Schema)
