### ISSUE TITLE
Závěrečná prezentace + dokumentace

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-PB138-2016#49]
- [x] nastudovat rozsah co je potřeba na splnění
- [x] zjistit jak se pracuje s DocBook
- [x] začít připravovat prezentaci

---

relevantní:
- https://github.com/snurkabill/PB138_projekt/blob/master/src/main/sprava/book.xml

**Comment by sonicka** [comment]
**Výsledok projektu:**
• Repozitár obsahujúci zdrojové kódy
• Wiki stránky projektu
• Binárna distribúcia (spustiteľný kód, .jar, .war archív apod.)

**Pred obhajobou na stránkach projektu:** 
• Aktuálne informácie
• Finálna verzia programovej časti
• Dokumentácia a správy k projektom
• Použité knižnice a iné potrebné nástroje

**Dokumentácia:**
• Wiki stránky
• Záverečná správa od každého člena tímu obsahujúca popis jeho práce na projekte
• Komentáre zdrojových kódov
• JavaDoc (ak je výstupom projektu obecne použiteľné API)

**Záverečné správy:**
• _Vypracuje každý člen tímu zvlášť_
• Výsledok je primárne vo formáte _DocBook_ (z neho generované HTML alebo PDF, odkazovaný z webu projektu)

**Obhajoba:**
• 20 minút vrátane otázok a diskusie; max 15 minút vlastná obhajoba + elektronická prezentácia výsledkov (slidy, ukážky prístupné na sieti/notebooku) + vyhnúť sa zbytočným technickým detailom
• Vedúci tímu predstaví zadanie projektu, riešiteľský tím a stručne zhrnie výsledky.
• Každý člen tímu predstaví svoju časť projektu, použité technológie a architektúru.
• Diskusia.

**Hodnotenie projektu:**
_Pre zisk bodového ohodnotenia je nutné, aby bol projekt úspešne vyriešený, bez vykazovania zásadných chýb._
• Vlastné riešenie (18 b) – splnenie zadania, kvalita riešenia, adekvátnosť použitých prostriedkov
• Obhajoba (8 b) – jej príprava a prevedenie
• Dokumentácia (8 b) – popis a wiki projektu; správy riešiteľov
• Riadenie a organizácia (14 b) – dodržanie kontrolných bodov; použitie podporných nástrojov (git)
