### ISSUE TITLE
Drill API

### ISSUE THREAD

**Issue by fprochazka** [fprochazka/fi-muni-PB138-2016#8]
- server-side aplikace v Javě
  - https://projects.spring.io/spring-framework/
- controllery s API (authentizace?)
  - použít [Apiary](https://apiary.io/how-it-works) na návrh
  - `POST /user` - registrace
  - `POST /authenticate`  - přihlášení
  - `POST /drill` vytvoření drillu
  - `POST /drill-from-qref` vytvoření drillu z odpovědníkového formátu (domyslet)
  - `POST /drill/{drillId}/question` přidání otázky
  - `PUT /drill/{drillId}/question/{questionId}` update otázky (včetně odpovědí)
  - `GET /drill/{drillId}` info o drillu a výpis otázek
  - `GET /drill/{drillId}/question/{questionId}` vrátí otázku
  - `POST /user/{userId}/exam/` <- `{drillId}`, založí nový "průchod odpovědníkem" a vrátí otázky a ID "examu"
  - `GET /user/{userId}/exam/` vrátí historii "průchodů" odpovědníky
  - `POST /user/{userId}/exam/{examId}/question/{questionId}` <- odpovídání na otázku - vrátí jestli odpověděl správně
  - `GET /user/{userId}/exam/{examId}` vrátí statistiky pro jednotlivé otázky
- modelová vrstva s logikou
  - parsování odpovědníkového formátu z IS
  - editovat můžou pouze registrovaní, ale můžou editovat cokoliv (wiki style)
  - pro každý drill bude možno pro uživatele založit jenom 1 exam, ve kterém se bude ukládat kompletní progress pro ten konkrétní drill
- persistenční vrstva
  - XML databáze - vybrat https://cs.wikiversity.org/wiki/XML_datab%C3%A1ze

**Comment by VikiVozarova** [comment]
Odpovede: pre danú otázku si pamätaj počet správnych a nesprávnych odpovedí, prioritne vyberaj najmenší sučet (počet odpovedí), sekundárne vyberaj najväčší počet nesprávnych odpovedí.

Posielať na clienta zoznam všetkých otázok zo štatistikami. Ukladanie na server v rozumných intervaloch - asynchronne s odpovedaním (local storage), nemeniť už v prijatých otázkach.

Apiary - návrh interface medzi Java a JavaScript
